### PR TITLE
🔧🔒 Configure RubyGems Trusted Publishing

### PR DESCRIPTION
**Pull request by nevans**
This requires additional configuration on the RubyGems website:
* https://guides.rubygems.org/trusted-publishing/adding-a-publisher/
* https://rubygems.org/gems/net-imap/trusted_publishers

### CODE REVIEW

**Comment by nevans** [comment]
@hsbt Have any other bundled gems configured trusted publishing yet?  I've configured this to run when pushing a specific tag pattern, but perhaps it should be triggered by some other event?  I want to be sure it doesn't conflict with any of your existing tools or processes.

**Comment by hsbt** [comment]
@nevans Nice work. We didn't use `release-gem` action under ruby org yet. If you have extra permission for this, let me know it.

I'm +1 to use this automation to other bundled gems 👍

**Comment by nevans** [comment]
@hsbt Great.  I'll test it out on the next release.

**Comment by nevans** [comment]
@hsbtLooking at other gems, I see three basic approaches to triggering:

    on push to a version tag (what we have here)
    on creation of a GitHub release
    on workflow_dispatch (triggered manually or by some other process)

I personally prefer the tag-based approach.


I _believe_ the default repository permissions prevent tag creation by non-maintainers.  But I also added a tag protection rule on `v*` and very basic branch protection on `master` (which can be dismissed by repository admins).

**Comment by nevans** [comment]
@hsbt I added made a couple of minor changes to the workflow:

* I added another job step to also draft a GitHub Release.
* I added a `RubyGems` environment.

Looking at other gems that have configured this (and came up in my code search), I saw three basic approaches to triggering:
* on push to a version tag (what we have here)
* on creation of a GitHub release
* on workflow_dispatch (triggered manually or by some other process)

I personally prefer the tag-based approach.  When combined with the `gh release create --draft`, it partially automates the creation of GitHub release.  When combined with a GitHub environment, the environment can be configured to require deployment approval (which serves the same function as workflow_dispatch for me).

I made the following other changes, too:
* I configured the "Trusted Publisher" on RubyGems.org.
* I configured the "RubyGems" environment on GitHub.
* I added a tag protection rule on `v*`.
* I added very basic branch protection on `master` (which can be dismissed by repository admins).

**Comment by nevans** [comment]
@hsbt @segiddins FYI: v0.4.11 used this.  It all seemed to work correctly.

**Comment by hsbt** [comment]
Great, thanks!

**Pull request merged**
