### PR TITLE
✨ Parse UTF-8 encoded strings, for UTF8=ACCEPT and IMAP4rev2

### LINKED ISSUE #38: `RFC6855` (2013): `UTF8=ACCEPT` (recommended by `IMAP4rev2` for backward compatibility)
n.b. RFC6855 (2013) obsoletes RFC5738 (2010)

### LINKED ISSUE #109: After ENABLE, IMAP4rev2 human-readable response text can include non-ASCII encoded in UTF-8.
MAP4rev2, Appendix E, 24.

### LINKED ISSUE #110: resp-text ABNF non-terminal was updated to allow for empty text.
IMAP4rev2, Appendix E, 23.

### PR DESCRIPTION
**Pull request by nevans**
Split off from #104, this PR updates how `text` and `quoted` are handled (without the other bugfixes and updates in that PR).

* Fixes #110
* Fixes #38
* Fixes #109

### CODE REVIEW

**Comment by arnt** [comment]
Wow, that's nice. I wrote the same thing while I was away being teambuilt, and discovered yours while making a pull request. A joyous kind of disappointment, if you see what I mean.

Mine has a couple of details I like better (if I've understood the diff correctly), I may make a tiny PR for those. But as it stands, great work, I'm so happy. Once ruby/net-smtp#49 is merged Ruby will have fine support for EAI.

**Comment by nevans** [comment]
@arnt Sorry about that!  It's a good problem to have, and honestly I might still be sitting on my code in privat branch if you hadn't beaten me to the `ENABLE` PR.  😉  I understand this joyous disappointment well!

And, I actually just came here to send you a note and ask if you had any thoughts on this PR!  In addition to your note on the  other PR, I knew from looking up your github profile that you had experience with email UTF-8 encoding.  And later when I was searching extra-wg mailing list archives I saw your name in there too!  So I figured you had experience that was well worth consulting. 🙂

I look forward to any thoughts you have to offer, and... I'm gonna race you to finish my `QRESYNC` PR first, too. 😜

**Comment by nevans** [comment]
@arnt BTW, if you want to simply make fake "PR" against the earlier version of the code, I'd be happy to take a look at that, too.

**Comment by arnt** [comment]
I'll be glad to review it, preferably next week, when I have two eleven-hour flights. This week I have lots to do. I'll push the branch again, though.

**Comment by arnt** [comment]
Looks good to me. Better than my code, which was perhaps overly optimised for being a small diff.

I see 'git push'  didn't recreate the branch I had deleted. No matter. I made a PR with the bits I had that weren't in your code. Really just details.

Thanks for doing this. I think I'll check mikelmail+arabic next.

**Comment by arnt** [comment]
One other thing. I can't race you on qresync. I can do favours, and will ;) but my job description says I should make EAI/IDN work better, find and fix interop problems, all that kind of thing. There's enough of it to keep me busy for a long time.

**Pull request merged**
