### PR TITLE
🔒 Add SASL SCRAM-SHA-* mechanisms

### LINKED ISSUE #54: SCRAM-SHA-1(-PLUS) + SCRAM-SHA-256(-PLUS) + SCRAM-SHA-512(-PLUS) + SCRAM-SHA3-512(-PLUS) supports
Dear @ruby team,

In first, I wish you a Happy New Year!

Can you add supports of :
- SCRAM-SHA-1
- SCRAM-SHA-1-PLUS
- SCRAM-SHA-256
- SCRAM-SHA-256-PLUS
- SCRAM-SHA-512
- SCRAM-SHA-512-PLUS
- SCRAM-SHA3-512
- SCRAM-SHA3-512-PLUS

You can add too:
- SCRAM-SHA-224
- SCRAM-SHA-224-PLUS
- SCRAM-SHA-384
- SCRAM-SHA-384-PLUS

"When using the SASL SCRAM mechanism, the SCRAM-SHA-256-PLUS variant SHOULD be preferred over the SCRAM-SHA-256 variant, and SHA-256 variants [RFC7677] SHOULD be preferred over SHA-1 variants [RFC5802]".

- SCRAM-SHA-1(-PLUS):
-- https://tools.ietf.org/html/rfc5802
-- https://tools.ietf.org/html/rfc6120

- SCRAM-SHA-256(-PLUS):
-- https://tools.ietf.org/html/rfc7677 since 2015-11-02
-- https://tools.ietf.org/html/rfc8600 since 2019-06-21: https://mailarchive.ietf.org/arch/msg/ietf-announce/suJMmeMhuAOmGn_PJYgX5Vm8lNA

- SCRAM-SHA-512(-PLUS):
-- https://tools.ietf.org/html/draft-melnikov-scram-sha-512

- SCRAM-SHA3-512(-PLUS):
-- https://tools.ietf.org/html/draft-melnikov-scram-sha3-512

https://xmpp.org/extensions/inbox/hash-recommendations.html

-PLUS variants:
- RFC5056: On the Use of Channel Bindings to Secure Channels: https://tools.ietf.org/html/rfc5056
- RFC5929: Channel Bindings for TLS: https://tools.ietf.org/html/rfc5929
- Channel-Binding Types: https://www.iana.org/assignments/channel-binding-types/channel-binding-types.xhtml
- RFC 9266: Channel Bindings for TLS 1.3: https://tools.ietf.org/html/rfc9266

IMAP:
- RFC9051: Internet Message Access Protocol (IMAP) - Version 4rev2: https://tools.ietf.org/html/rfc9051

LDAP:
- RFC5803: Lightweight Directory Access Protocol (LDAP) Schema for Storing Salted: Challenge Response Authentication Mechanism (SCRAM) Secrets: https://tools.ietf.org/html/rfc5803

HTTP:
- RFC7804: Salted Challenge Response HTTP Authentication Mechanism: https://tools.ietf.org/html/rfc7804

2FA:
- Extensions to Salted Challenge Response (SCRAM) for 2 factor authentication: https://tools.ietf.org/html/draft-melnikov-scram-2fa

IANA:
- Simple Authentication and Security Layer (SASL) Mechanisms: https://www.iana.org/assignments/sasl-mechanisms/sasl-mechanisms.xhtml

Linked to:
- https://github.com/scram-xmpp/info/issues/1

### PR DESCRIPTION
**Pull request by nevans**
Loosely based an initial implementation by @singpolyma at
https://github.com/nevans/net-sasl/pull/5

* Depends on #179
* Fixes #54

### CODE REVIEW

**Comment by nevans** [comment]
I've delayed finishing this PR for ~a year now?  Unfortunately, I haven't had much cause to use this myself (`OAUTHBEARER` support was more immediately useful for my needs).

As far as the authenticator API (expanded to include `#initial_response?` and `#done?`) is concerned, it's basically done... although I would really appreciate another pair of eyes on the implementation!

However, `Net::IMAP#authenticate` still needs to be updated so it ensures the authenticator is `#done?`.  As it is now, if the server returns `OK` before sending its final message, then we can't satisfy the following requirement from the RFC:
> The client then authenticates the server by computing the
> ServerSignature and comparing it to the value sent by the server.  If
> the two are different, the client MUST consider the authentication
> exchange to be unsuccessful, and it might have to drop the
> connection.

**Comment by nevans** [comment]
@singpolyma, @Neustradamus FYI: This has been merged and I'm going to make a new release containing it this week (maybe today or tomorrow?).  If you have any time to look over what I've done and test it a little bit, I'd be grateful.

**Comment by Neustradamus** [comment]
@singpolyma: Can you look?

**Comment by Neustradamus** [comment]
@nevans: Excellent, thanks!

Have you plan a net-sasl build with?
- https://github.com/nevans/net-sasl

Have you looked for -PLUS variants part?

@singpolyma: Can you look?

**Pull request merged**
